### ISSUE TITLE
data

### ISSUE THREAD

**Issue by hidfgidh** [ActiveVisionLab/NeFeS#2]
Hello, I encountered an error while executing the following command
![捕获](https://github.com/user-attachments/assets/d7a6e6cc-db02-4ab4-ac8a-75852b4abb04)

After executing your command, the original dataset can be downloaded, but when executing the command

[  semantic = ['https://www.robots.ox.ac.uk/~shuaic/NeFeS2024/Cambridge_semantic.zip']，](https://github.com/ActiveVisionLab/NeFeS/blob/f954c5fc6d844eb81e01c02236e0706c32e19e85/data/setup_cambridge.py#L19)

the data is incomplete.
![捕获](https://github.com/user-attachments/assets/89db7486-f459-46a2-9791-8b2176875fe5)

The original dataset had 5 scenarios, but this compressed file only contains 4

The downloaded and decompressed file is shown in the picture
![捕获](https://github.com/user-attachments/assets/ef439750-c404-440e-9647-2dc66c1cdb4e)

**Comment by chenusc11** [comment]
Ah, I think you are right. Thanks for the question. Apologize for my negligence.

Since in our paper, we only compared four scenes to align with previous works. I don't remember if I have actually run GreatCourt semantic map. If I remember correctly, there aren't many temporal objects in this specific scene, therefore semantic filtering may also not be necessary.

For now, maybe you could comment out this line so there is no bug: https://github.com/ActiveVisionLab/NeFeS/blob/f954c5fc6d844eb81e01c02236e0706c32e19e85/data/setup_cambridge.py#L16

When I get home today, I could try to see if I can find GreatCourt semantic maps and fix the script issue.

**Comment by hidfgidh** [comment]
Thank you for your answer
